name: push docker image

on:
  push:
    branches:
      - main
      - rc-*
      - 9c-main
      - development
      - previewnet
      - qa-*
      - 2022q3-worldboss
    tags:
      - v*
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Custom docker image tag if needed'
        default: ''

env:
  DOCKER_REPO: planetariumhq/ninechronicles-headless

jobs:
  build_and_push:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: login
        run: |
          docker login \
            --username '${{ secrets.DOCKER_USERNAME }}' \
            --password '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
      - name: setup-qemu
        run: |
          docker run --rm --privileged multiarch/qemu-user-static \
            --reset \
            -p yes
      - name: build-and-push-amd64
        run: |
          docker build . \
            -f Dockerfile.amd64 \
            -t $DOCKER_REPO:git-${{ github.sha }}-amd64 \
            --build-arg COMMIT=git-${{ github.sha }}
          docker push $DOCKER_REPO:git-${{ github.sha }}-amd64
      - name: build-and-push-arm64v8
        run: |
          docker build . \
            -f Dockerfile.arm64v8 \
            -t $DOCKER_REPO:git-${{ github.sha }}-arm64v8 \
            --build-arg COMMIT=git-${{ github.sha }}
          docker push $DOCKER_REPO:git-${{ github.sha }}-arm64v8
      - name: merge-manifest-and-push
        run: |
          docker manifest create $DOCKER_REPO:git-${{ github.sha }} \
            --amend $DOCKER_REPO:git-${{ github.sha }}-amd64 \
            --amend $DOCKER_REPO:git-${{ github.sha }}-arm64v8
          docker manifest push $DOCKER_REPO:git-${{ github.sha }}

  tag:
    if: ${{ github.ref_type == 'tag' || github.events.inputs.imageTag != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: login
        run: |
          docker login \
            --username '${{ secrets.DOCKER_USERNAME }}' \
            --password '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
      - name: push git tagged version
        run: |
          docker pull $DOCKER_REPO:git-${{ github.sha }}-amd64
          if [[ -z ${{ github.events.inputs.imageTag }} ]]; then
            export IMAGE_TAG=${{ github.events.inputs.imageTag }}
          else
            export IMAGE_TAG=${{ github.ref_name }}
          fi

          docker tag \
            $DOCKER_REPO:git-${{ github.sha }}-amd64 \
            $DOCKER_REPO:$IMAGE_TAG-amd64
          docker push $DOCKER_REPO:$IMAGE_TAG-amd64
          docker pull $DOCKER_REPO:git-${{ github.sha }}-arm64v8
          docker tag \
            $DOCKER_REPO:git-${{ github.sha }}-arm64v8 \
            $DOCKER_REPO:$IMAGE_TAG-arm64v8
          docker push $DOCKER_REPO:$IMAGE_TAG-arm64v8
          docker manifest create $DOCKER_REPO:$IMAGE_TAG \
            --amend $DOCKER_REPO:$IMAGE_TAG-amd64 \
            --amend $DOCKER_REPO:$IMAGE_TAG-arm64v8
          docker manifest push $DOCKER_REPO:$IMAGE_TAG
