name: test docker

on:
  push:
    branches:
      - main
      - rc-*
      - 9c-main
      - development
      - previewnet
      - qa-*
      - 2022q3-worldboss
    tags:
      - v*
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Custom docker image tag if needed'
        default: ''

env:
  DOCKER_REPO: planetariumhq/ninechronicles-headless

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print input
        run: |
          set -ex
          echo ${{ github.event.inputs.imageTag }}
          if [[ ${{ github.event.inputs.imageTag != '' }} ]]; then
            echo "not empty"
          else
            echo "empty"
          fi

  test:
    if: github.ref_type == 'tag' || github.event.inputs.imageTag != ''
    runs-on: ubuntu-latest
    steps:
      - name: push git tagged version
        run: |
          docker pull $DOCKER_REPO:git-${{ github.sha }}-amd64
          if [[ -z ${{ github.event.inputs.imageTag }} ]]; then
            export IMAGE_TAG=${{ github.event.inputs.imageTag }}
          else
            export IMAGE_TAG=${{ github.ref_name }}
          fi

          docker tag \
            $DOCKER_REPO:git-${{ github.sha }}-amd64 \
            $DOCKER_REPO:$IMAGE_TAG-amd64
          docker pull $DOCKER_REPO:git-${{ github.sha }}-arm64v8
          docker tag \
            $DOCKER_REPO:git-${{ github.sha }}-arm64v8 \
            $DOCKER_REPO:$IMAGE_TAG-arm64v8
